pipeline:
  build_test:
    image: node:${NODE_VERSION}
    environment:
      - NPM_CONFIG_LOGLEVEL=silent
    commands:
      - npm install
      - npm test

  publish_coverage:
    image: plugins/coverage
    pattern: docs/code-coverage/lcov.info
    when:
      matrix:
        NODE_VERSION: 6

  # Semantic versioning release control
  run_semantique_self:
    image: eventualconsistency/semantique
    pull: true
    when:
      branch: master
      event: push

  # NPM Publishing on tagging from semantique
  npm_publish:
    image: plugins/npm
    when:
      event: tag

matrix:
  NODE_VERSION:
    - 4
    - 5
    - 6
    - 7
    - latest
