pipeline:
  install_npm_packages:
    image: node:${NODE_VERSION}
    commands:
      - npm install
  run_unit_tests:
    image: node:${NODE_VERSION}
    commands:
      - npm install gulp -g
      - gulp
  apply_npm_version:
    image: node:${NODE_VERSION}
    commands:
      - git config --global user.name "Drone CI"
      - git config --global user.email "drone@eventualconsistency.net"
      - npm version ${DRONE_TAG} || true
    when:
      event: tag
      matrix:
        NODE_VERSION: 6.0

matrix:
  NODE_VERSION:
    - latest
    - 6.3
    - 6.0
    - 5.5
    - 5.2
    - 4.1
    - 4.0
