pipeline:
  install_npm_packages:
    image: node:${NODE_VERSION}
    commands:
      - npm install --silent --loglevel silent
  run_unit_tests:
    image: node:${NODE_VERSION}
    commands:
      - npm install gulp -g --silent --loglevel silent
      - gulp
  apply_npm_version:
    image: node:${NODE_VERSION}
    commands:
      - git config --global user.name "Drone CI"
      - git config --global user.email "drone@eventualconsistency.net"
      - npm version ${DRONE_TAG} || true
    when:
      event: tag
      matrix:
        NODE_VERSION: 6.0

matrix:
  NODE_VERSION:
    - latest
    - 6
    - 5
    - 4
