pipeline:
  build_test:
    image: node:${NODE_VERSION}
    environment:
      - NPM_CONFIG_LOGLEVEL=silent
    commands:
      - npm install
      - npm test

  publish_coverage:
    image: plugins/coverage
    pattern: docs/code-coverage/lcov.info
    when:
      matrix:
        NODE_VERSION: 6

  apply_npm_version:
    image: node:${NODE_VERSION}
    commands:
      - git config --global user.name "Drone CI"
      - git config --global user.email "drone@eventualconsistency.net"
      - npm version ${DRONE_TAG} || true
    when:
      event: tag

  deploy_npm_package:
    image: plugins/npm
    when:
      event: tag
      matrix:
        NODE_VERSION: 6

matrix:
  NODE_VERSION:
    - 4
    - 5
    - 6
    - latest
