debug: true
pipeline:
  build_test:
    image: node:${NODE_VERSION}
    environment:
      - NPM_CONFIG_LOGLEVEL=silent
    commands:
      - npm install
      - npm test

  apply_npm_version:
    image: node:${NODE_VERSION}
    commands:
      - git config --global user.name "Drone CI"
      - git config --global user.email "drone@eventualconsistency.net"
      - npm version ${DRONE_TAG} || true
    when:
      event: tag
      matrix:
        NODE_VERSION: 6

matrix:
  NODE_VERSION:
    - latest
    - 6
    - 5
    - 4
